version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6
    container_name: shopsphere-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: shopsphere
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shopsphere-network

  # Backend API
  backend:
    build: ./backend
    container_name: shopsphere-backend
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/shopsphere?authSource=admin
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - shopsphere-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (Nginx)
  frontend:
    image: nginx:alpine
    container_name: shopsphere-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - shopsphere-network

volumes:
  mongodb_data:

networks:
  shopsphere-network:
    driver: bridge
